import torch
from nltk.translate.bleu_score import corpus_bleu
from inference import CaptionGenerator
from data_loader import get_loader, get_transforms
from tqdm import tqdm

def calculate_bleu_score(model, data_loader, vocab, device, beam_size=3):
    """
    Evaluates the model on the test dataset and calculates BLEU-4 score.
    """
    model.eval()
    generator = CaptionGenerator(model, vocab, device)
    
    references = []
    hypotheses = []
    
    with torch.no_grad():
        for images, captions in tqdm(data_loader, desc="Evaluating BLEU-4"):
            images = images.to(device)
            # encoder_out = model.encoder(images) # Not needed here as we use generator
            
            for i in range(images.size(0)):
                # Original captions for reference
                ref = [vocab.itos[idx.item()] for idx in captions[i] if idx not in [vocab.stoi["<SOS>"], vocab.stoi["<EOS>"], vocab.stoi["<PAD>"]]]
                references.append([ref])
                
                # Hypothesis generated by model
                hyp = generator.generate_caption_beam_search(images[i].cpu(), beam_size=beam_size)
                hypotheses.append(hyp)
                
    bleu4 = corpus_bleu(references, hypotheses)
    print(f"BLEU-4 Score: {bleu4:.4f}")
    return bleu4

if __name__ == "__main__":
    # Example usage for standalone evaluation
    pass
